name: upper-capture

on:
  push:
    paths:
      - 'upper/**'
      - '.github/workflows/upper-cross.yaml'
      - 'README.md'
      
  workflow_dispatch: #manual

jobs:
  cross:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - run: ls 
#      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: 'upper/go.sum'
      - run: go mod download
        working-directory: upper
      - run: ./build.xplat.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: upper/bin/upper*
          body: "Binaries for the upper (go) command line tool !!"
          tag_name: ${{ github.ref_name }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: upper/bin/upper*


    