name: upper-capture

on:
  push:
    paths:
      - 'upper/**'
      - '.github/workflows/upper-capture.yaml'
      - 'README.md'
      
  workflow_dispatch: #manual

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - run: pwd && ls -al
#      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: 'upper/go.sum'
      - run: go mod download
        working-directory: upper
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - uses: actions/upload-artifact@v4
        with:
          name: upper-capture
          path: upper/upper


    